### ISSUE TITLE
Writeup for cool kicks challenge

### ISSUE THREAD

**Issue by mar232320** [hypnogod/FreedomCTFWriteUps#1]
Hello, I participated in freedom ctf in june and I greatly enjoyed it. Could you tell me what is the solution of cool kicks challenge? I found out that its truecrypt steganography but doesnt for for rockyou in hashcat

**Comment by s-sanskar** [comment]
You should join the discord: https://discord.gg/qYaXgsENgX and contact IfLOP and drMoscovium

**Comment by mar232320** [comment]
what if i dont have an account there?
Are there any other contact options 
I've written an email to freedomc7f@gmail.com

**Comment by s-sanskar** [comment]
Hello @mar232320 , I don't have a way to help you since I am not familiar with this question. I have asked the creator of the question, and he told me the password is not inside of rockyou.txt. He didn't provide me with any other hints. My suggestion would be to use another wordlist or use words inside of freedomCTF websites.

I highly recommend you create one if you don't have discord since most CTF use discord. 

FreedomCTF is currently going through some changes, so it will not be available for a couple of months and you might not get any response from freedomc7f@gmail.com anytime soon.

**Comment by s-sanskar** [comment]
UPDATE: I don't think freedomc7f@gmail.com or the question creator will give you the flag since they are planing on reusing Cool Kicks. If you have any other questions you need to ask them directly using discord. Sorry for the inconvenience.

**Comment by mar232320** [comment]
@hypnogod OK, no problem
